export const ENVIRONEMNT_KEYS = {
    BASE_HOST: 'VITE_BASE_HOST',
    AUTHENTICATION_API_HOST: 'VITE_AUTHENTICATION_API_HOST',
    ENV: 'VITE_ACTIVE_ENVIRONMENT',
    GOOGLE_AUTHENTICATION_CLIENT_ID: 'VITE_AUTHENTICATION_CLIENT_ID'
}

export const ENVIRONEMNTS = {
    LOCAL: 'local',
    LOCAL_TO_DEV: 'local-to-dev',
    DEVELOPMENT: 'dev',
}